// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvJahnOrchesterApp.Infrastructure.Persistence;

#nullable disable

namespace TvJahnOrchesterApp.Infrastructure.Migrations
{
    [DbContext(typeof(OrchesterDbContext))]
    [Migration("20230929115210_UpdateOrchestermitglied")]
    partial class UpdateOrchestermitglied
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Geburtstag")
                        .HasColumnType("datetime2");

                    b.Property<string>("Handynummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterKeyExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UserFirstConnected")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedUserId")
                        .IsUnique()
                        .HasFilter("[ConnectedUserId] IS NOT NULL");

                    b.ToTable("Orchestermitglieder", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.TerminAggregate.Termin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TerminId");

                    b.Property<Guid?>("AbstimmungsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TerminArt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Termine", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.UserAggregate.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OrchesterMitgliedsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrchesterMitgliedsId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithOne()
                        .HasForeignKey("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", "ConnectedUserId");

                    b.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hausnummer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("Longitide")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Postleitzahl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Stadt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Straße")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Zusatz")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Instrument", "DefaultInstrument", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ArtInstrument")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Notenstimme", "DefaultNotenStimme", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Stimme")
                                .HasColumnType("int");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.OwnsOne("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.ValueObjects.MitgliedsStatus", "OrchesterMitgliedsStatus", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MitgliedsStatusEnum")
                                .HasColumnType("int");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("DefaultInstrument")
                        .IsRequired();

                    b.Navigation("DefaultNotenStimme")
                        .IsRequired();

                    b.Navigation("OrchesterMitgliedsStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.TerminAggregate.Termin", b =>
                {
                    b.OwnsOne("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.EinsatzPlan", "EinsatzPlan", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("EinsatzplanId");

                            b1.Property<Guid>("TerminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndZeit")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartZeit")
                                .HasColumnType("datetime2");

                            b1.Property<string>("WeitereInformationen")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id", "TerminId");

                            b1.HasIndex("TerminId")
                                .IsUnique();

                            b1.ToTable("Einsatzpläne", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TerminId");

                            b1.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Treffpunkt", b2 =>
                                {
                                    b2.Property<Guid>("EinsatzPlanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("EinsatzPlanTerminId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Hausnummer")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<decimal?>("Latitude")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal?>("Longitide")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Postleitzahl")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Stadt")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Straße")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Zusatz")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("EinsatzPlanId", "EinsatzPlanTerminId");

                                    b2.ToTable("Einsatzpläne");

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzPlanId", "EinsatzPlanTerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.ZeitBlock", "ZeitBlocks", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("EinsatzplanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("TerminId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Beschreibung")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("Endzeit")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Startzeit")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("Id", "EinsatzplanId", "TerminId");

                                    b2.HasIndex("EinsatzplanId", "TerminId");

                                    b2.ToTable("Zeitblöcke", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzplanId", "TerminId");

                                    b2.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Adresse", b3 =>
                                        {
                                            b3.Property<Guid>("ZeitBlockId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("ZeitBlockEinsatzplanId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("ZeitBlockTerminId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Hausnummer")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<decimal?>("Latitude")
                                                .HasColumnType("decimal(18,2)");

                                            b3.Property<decimal?>("Longitide")
                                                .HasColumnType("decimal(18,2)");

                                            b3.Property<string>("Postleitzahl")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Stadt")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Straße")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Zusatz")
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("ZeitBlockId", "ZeitBlockEinsatzplanId", "ZeitBlockTerminId");

                                            b3.ToTable("Zeitblöcke");

                                            b3.WithOwner()
                                                .HasForeignKey("ZeitBlockId", "ZeitBlockEinsatzplanId", "ZeitBlockTerminId");
                                        });

                                    b2.Navigation("Adresse");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.ValueObjects.Noten", "Noten", b2 =>
                                {
                                    b2.Property<Guid>("EinsatzplanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("TerminId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("NotenEnum")
                                        .HasColumnType("int");

                                    b2.HasKey("EinsatzplanId", "TerminId", "Id");

                                    b2.ToTable("EinsatzplanNoten", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzplanId", "TerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.ValueObjects.Uniform", "Uniform", b2 =>
                                {
                                    b2.Property<Guid>("EinsatzplanId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("TerminId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("UniformEnum")
                                        .HasColumnType("int");

                                    b2.HasKey("EinsatzplanId", "TerminId", "Id");

                                    b2.ToTable("EinsatzplanUniform", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzplanId", "TerminId");
                                });

                            b1.Navigation("Noten");

                            b1.Navigation("Treffpunkt")
                                .IsRequired();

                            b1.Navigation("Uniform");

                            b1.Navigation("ZeitBlocks");
                        });

                    b.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.TerminRückmeldungOrchestermitglied", "TerminRückmeldungOrchesterMitglieder", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TerminRückmeldungsId");

                            b1.Property<Guid>("TerminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IstAnwesend")
                                .HasColumnType("bit");

                            b1.Property<string>("KommentarAnwesenheit")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("KommentarZusage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("LetzteRückmeldung")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("OrchesterMitgliedsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("RückmeldungDurchAnderesOrchestermitglied")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Zugesagt")
                                .HasColumnType("int");

                            b1.HasKey("Id", "TerminId");

                            b1.HasIndex("TerminId");

                            b1.ToTable("TerminRückmeldungen", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TerminId");

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.Common.ValueObjects.Instrument", "Instruments", b2 =>
                                {
                                    b2.Property<Guid>("TerminRückmeldungsId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("TerminId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("ArtInstrument")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("TerminRückmeldungsId", "TerminId", "Id");

                                    b2.ToTable("RückmeldungInstruments", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TerminRückmeldungsId", "TerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.Common.ValueObjects.Notenstimme", "Notenstimme", b2 =>
                                {
                                    b2.Property<Guid>("TerminRückmeldungsId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("TerminId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Stimme")
                                        .HasColumnType("int");

                                    b2.HasKey("TerminRückmeldungsId", "TerminId", "Id");

                                    b2.ToTable("RückmeldungNotenstimmen", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TerminRückmeldungsId", "TerminId");
                                });

                            b1.Navigation("Instruments");

                            b1.Navigation("Notenstimme");
                        });

                    b.Navigation("EinsatzPlan")
                        .IsRequired();

                    b.Navigation("TerminRückmeldungOrchesterMitglieder");
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.UserAggregate.User", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", null)
                        .WithOne()
                        .HasForeignKey("TvJahnOrchesterApp.Domain.UserAggregate.User", "OrchesterMitgliedsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
