// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvJahnOrchesterApp.Infrastructure.Persistence;

#nullable disable

namespace TvJahnOrchesterApp.Infrastructure.Migrations
{
    [DbContext(typeof(OrchesterDbContext))]
    [Migration("20230830060821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultNotenStimme")
                        .HasColumnType("int");

                    b.Property<DateTime>("Geburtstag")
                        .HasColumnType("datetime2");

                    b.Property<string>("Handynummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orchestermitglieder", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", b =>
                {
                    b.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hausnummer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("Longitide")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Postleitzahl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Stadt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Straße")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Zusatz")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Instrument", "DefaultInstrument", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ArtInstrument")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("DefaultInstrument")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
