// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TvJahnOrchesterApp.Infrastructure.Persistence;

#nullable disable

namespace TvJahnOrchesterApp.Infrastructure.Migrations
{
    [DbContext(typeof(OrchesterDbContext))]
    partial class OrchesterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.ArtInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArtInstrument", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Holz"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Blech"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Schlagwerk"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Dirigent"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtInstrumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtInstrumentId");

                    b.ToTable("Instrumente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtInstrumentId = 1,
                            Value = "Saxophon"
                        },
                        new
                        {
                            Id = 2,
                            ArtInstrumentId = 2,
                            Value = "Trompete"
                        },
                        new
                        {
                            Id = 3,
                            ArtInstrumentId = 3,
                            Value = "Trommel"
                        },
                        new
                        {
                            Id = 4,
                            ArtInstrumentId = 4,
                            Value = "Dirigent"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.MitgliedsStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MitgliedsStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "aktiv"
                        },
                        new
                        {
                            Id = 2,
                            Value = "passiv"
                        },
                        new
                        {
                            Id = 3,
                            Value = "ausgetreten"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Noten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Noten", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Schwarzes Marschbuch"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Blaues Marschbuch"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Rotes Marschbuch"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Konzertmappe"
                        },
                        new
                        {
                            Id = 6,
                            Value = "St. Martin Noten"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Karnevalsnoten"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Weihnachtsnoten"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Notenstimme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notenstimme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Alt Saxophon 1"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Alt Saxophon 2"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Sopran Saxophon"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Trompete 1"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Trompete 2"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Trompete 3"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Schlagzeug"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Dirigent"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Obmann"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Kassierer"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Notenwart"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Zeugwart"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Thekenteam"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Rückmeldungsart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rückmeldungsarten", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Nicht Zurückgemeldet"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Zugesagt"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Abgesagt"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.TerminArt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TerminArten", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Auftritt"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Konzert"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Probe"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Freizeit"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Reise"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.TerminStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TerminStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Angefragt"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Zugesagt"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Abgesagt"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Uniform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Uniform", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Blaues Hemd"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Weiße Hose"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Winter Jacke"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Zivil"
                        });
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("OrchesterMitgliedsId");

                    b.Property<string>("ConnectedUserId")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultInstrument")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultNotenStimme")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Geburtstag")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Handynummer")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MemberSinceInYears")
                        .HasColumnType("integer");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrchesterMitgliedsStatus")
                        .HasColumnType("integer");

                    b.Property<string>("RegisterKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterKeyExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefonnummer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UserFirstConnected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UserLastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedUserId")
                        .IsUnique();

                    b.HasIndex("DefaultInstrument");

                    b.HasIndex("DefaultNotenStimme");

                    b.HasIndex("OrchesterMitgliedsStatus");

                    b.ToTable("Orchestermitglieder", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.TerminAggregate.Termin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("TerminId");

                    b.Property<Guid?>("AbstimmungsId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TerminArt")
                        .HasColumnType("integer");

                    b.Property<int?>("TerminStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TerminArt");

                    b.HasIndex("TerminStatus");

                    b.ToTable("Termine", (string)null);
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.UserAggregate.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrchesterMitgliedsId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrchesterMitgliedsId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.Common.Entities.Instrument", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.ArtInstrument", null)
                        .WithMany()
                        .HasForeignKey("ArtInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.UserAggregate.User", null)
                        .WithOne()
                        .HasForeignKey("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", "ConnectedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("DefaultInstrument")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Notenstimme", null)
                        .WithMany()
                        .HasForeignKey("DefaultNotenStimme")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.MitgliedsStatus", null)
                        .WithMany()
                        .HasForeignKey("OrchesterMitgliedsStatus")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("OrchesterMitgliedId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hausnummer")
                                .HasColumnType("text");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Longitide")
                                .HasColumnType("numeric");

                            b1.Property<string>("Postleitzahl")
                                .HasColumnType("text");

                            b1.Property<string>("Stadt")
                                .HasColumnType("text");

                            b1.Property<string>("Straße")
                                .HasColumnType("text");

                            b1.Property<string>("Zusatz")
                                .HasColumnType("text");

                            b1.HasKey("OrchesterMitgliedId");

                            b1.ToTable("Orchestermitglieder");

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedId");
                        });

                    b.OwnsMany("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.Entities.OrchesterMitgliedPositionsMapping", "PositionMappings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("OrchesterMitgliedsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PositionId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("OrchesterMitgliedsId");

                            b1.HasIndex("PositionId");

                            b1.ToTable("OrchestermitgliedPositions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrchesterMitgliedsId");

                            b1.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Position", null)
                                .WithMany()
                                .HasForeignKey("PositionId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("PositionMappings");
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.TerminAggregate.Termin", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.TerminArt", null)
                        .WithMany()
                        .HasForeignKey("TerminArt")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.TerminStatus", null)
                        .WithMany()
                        .HasForeignKey("TerminStatus")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.EinsatzPlan", "EinsatzPlan", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("EinsatzplanId");

                            b1.Property<Guid>("TerminId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndZeit")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartZeit")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("WeitereInformationen")
                                .HasColumnType("text");

                            b1.HasKey("Id", "TerminId");

                            b1.HasIndex("TerminId")
                                .IsUnique();

                            b1.ToTable("Einsatzpläne", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TerminId");

                            b1.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Treffpunkt", b2 =>
                                {
                                    b2.Property<Guid>("EinsatzPlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("EinsatzPlanTerminId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Hausnummer")
                                        .HasColumnType("text");

                                    b2.Property<decimal?>("Latitude")
                                        .HasColumnType("numeric");

                                    b2.Property<decimal?>("Longitide")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Postleitzahl")
                                        .HasColumnType("text");

                                    b2.Property<string>("Stadt")
                                        .HasColumnType("text");

                                    b2.Property<string>("Straße")
                                        .HasColumnType("text");

                                    b2.Property<string>("Zusatz")
                                        .HasColumnType("text");

                                    b2.HasKey("EinsatzPlanId", "EinsatzPlanTerminId");

                                    b2.ToTable("Einsatzpläne");

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzPlanId", "EinsatzPlanTerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.EinsatzplanNotenMapping", "EinsatzplanNotenMappings", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid?>("EinsatzplanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("NotenId")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("TerminId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("NotenId");

                                    b2.HasIndex("EinsatzplanId", "TerminId");

                                    b2.ToTable("EinsatzplanNotenMapping", (string)null);

                                    b2.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Noten", null)
                                        .WithMany()
                                        .HasForeignKey("NotenId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzplanId", "TerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.EinsatzplanUniformMapping", "EinsatzplanUniformMappings", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid?>("EinsatzplanId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid?>("TerminId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("UniformId")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UniformId");

                                    b2.HasIndex("EinsatzplanId", "TerminId");

                                    b2.ToTable("EinsatzplanUniformMapping", (string)null);

                                    b2.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Uniform", null)
                                        .WithMany()
                                        .HasForeignKey("UniformId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzplanId", "TerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.ZeitBlock", "ZeitBlocks", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("EinsatzplanId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("TerminId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Beschreibung")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("Endzeit")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("Startzeit")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("Id", "EinsatzplanId", "TerminId");

                                    b2.HasIndex("EinsatzplanId", "TerminId");

                                    b2.ToTable("Zeitblöcke", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EinsatzplanId", "TerminId");

                                    b2.OwnsOne("TvJahnOrchesterApp.Domain.Common.ValueObjects.Adresse", "Adresse", b3 =>
                                        {
                                            b3.Property<Guid>("ZeitBlockId")
                                                .HasColumnType("uuid");

                                            b3.Property<Guid>("ZeitBlockEinsatzplanId")
                                                .HasColumnType("uuid");

                                            b3.Property<Guid>("ZeitBlockTerminId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Hausnummer")
                                                .HasColumnType("text");

                                            b3.Property<decimal?>("Latitude")
                                                .HasColumnType("numeric");

                                            b3.Property<decimal?>("Longitide")
                                                .HasColumnType("numeric");

                                            b3.Property<string>("Postleitzahl")
                                                .HasColumnType("text");

                                            b3.Property<string>("Stadt")
                                                .HasColumnType("text");

                                            b3.Property<string>("Straße")
                                                .HasColumnType("text");

                                            b3.Property<string>("Zusatz")
                                                .HasColumnType("text");

                                            b3.HasKey("ZeitBlockId", "ZeitBlockEinsatzplanId", "ZeitBlockTerminId");

                                            b3.ToTable("Zeitblöcke");

                                            b3.WithOwner()
                                                .HasForeignKey("ZeitBlockId", "ZeitBlockEinsatzplanId", "ZeitBlockTerminId");
                                        });

                                    b2.Navigation("Adresse");
                                });

                            b1.Navigation("EinsatzplanNotenMappings");

                            b1.Navigation("EinsatzplanUniformMappings");

                            b1.Navigation("Treffpunkt")
                                .IsRequired();

                            b1.Navigation("ZeitBlocks");
                        });

                    b.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.TerminRückmeldungOrchestermitglied", "TerminRückmeldungOrchesterMitglieder", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("TerminRückmeldungsId");

                            b1.Property<Guid>("TerminId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IstAnwesend")
                                .HasColumnType("boolean");

                            b1.Property<string>("KommentarAnwesenheit")
                                .HasColumnType("text");

                            b1.Property<string>("KommentarZusage")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LetzteRückmeldung")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("OrchesterMitgliedsId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("RückmeldungDurchAnderesOrchestermitglied")
                                .HasColumnType("uuid");

                            b1.Property<int>("Zugesagt")
                                .HasColumnType("integer");

                            b1.HasKey("Id", "TerminId");

                            b1.HasIndex("OrchesterMitgliedsId");

                            b1.HasIndex("RückmeldungDurchAnderesOrchestermitglied");

                            b1.HasIndex("TerminId");

                            b1.ToTable("TerminRückmeldungen", (string)null);

                            b1.HasOne("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", null)
                                .WithMany()
                                .HasForeignKey("OrchesterMitgliedsId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", null)
                                .WithMany()
                                .HasForeignKey("RückmeldungDurchAnderesOrchestermitglied");

                            b1.WithOwner()
                                .HasForeignKey("TerminId");

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.TerminRückmeldungInstrumentMapping", "TerminRückmeldungInstrumentMappings", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("InstrumentId")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("TerminId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid?>("TerminRückmeldungsId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("InstrumentId");

                                    b2.HasIndex("TerminRückmeldungsId", "TerminId");

                                    b2.ToTable("TerminRückmeldungInstrumentMapping", (string)null);

                                    b2.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Instrument", null)
                                        .WithMany()
                                        .HasForeignKey("InstrumentId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("TerminRückmeldungsId", "TerminId");
                                });

                            b1.OwnsMany("TvJahnOrchesterApp.Domain.TerminAggregate.Entities.TerminRückmeldungNotenstimmenMapping", "TerminRückmeldungNotenstimmenMappings", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("NotenstimmenId")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("TerminId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid?>("TerminRückmeldungsId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("NotenstimmenId");

                                    b2.HasIndex("TerminRückmeldungsId", "TerminId");

                                    b2.ToTable("TerminRückmeldungNotenstimmeMapping", (string)null);

                                    b2.HasOne("TvJahnOrchesterApp.Domain.Common.Entities.Notenstimme", null)
                                        .WithMany()
                                        .HasForeignKey("NotenstimmenId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("TerminRückmeldungsId", "TerminId");
                                });

                            b1.Navigation("TerminRückmeldungInstrumentMappings");

                            b1.Navigation("TerminRückmeldungNotenstimmenMappings");
                        });

                    b.Navigation("EinsatzPlan")
                        .IsRequired();

                    b.Navigation("TerminRückmeldungOrchesterMitglieder");
                });

            modelBuilder.Entity("TvJahnOrchesterApp.Domain.UserAggregate.User", b =>
                {
                    b.HasOne("TvJahnOrchesterApp.Domain.OrchesterMitgliedAggregate.OrchesterMitglied", null)
                        .WithOne()
                        .HasForeignKey("TvJahnOrchesterApp.Domain.UserAggregate.User", "OrchesterMitgliedsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
